name: MLflow CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install mlflow pandas scikit-learn docker

      - name: Run MLflow Training
        run: |
          cd MLProject
          mlflow run . --env-manager local
        
      - name: Archive Model Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: mlruns/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push MLflow Docker Image
        run: |
          # 1. Cari RUN_ID secara otomatis dari folder mlruns
          # Kita gunakan find untuk mencari folder 'model' di dalam direktori MLProject/mlruns
          MODEL_PATH=$(find MLProject/mlruns/0 -name "model" -type d | head -n 1)
          
          echo "Model ditemukan di: $MODEL_PATH"
          
          if [ -z "$MODEL_PATH" ]; then
            echo "Error: Folder model tidak ditemukan!"
            exit 1
          fi

          # 2. Build Docker menggunakan path absolut/relatif yang ditemukan
          # Kita gunakan flag -m dengan path langsung ke folder model
          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-model:latest" \
            --install-mlflow

          # 3. Push ke Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-model:latest